apiVersion: v1
kind: Pod
metadata:
  name: pokmon-pod
  labels:
    app: pokmon-pod
spec:
  containers:
  - name: pokmon-game-container
    image: sluu3/pokmongame
    imagePullPolicy: Always
    ports:
      - containerPort: 8080
        protocol: TCP
    #command: ['sh', '-c', 'echo The app is running!']
  #initContainers:
  - name: pokmon-server-container
    image: sluu3/pokmonserver
    imagePullPolicy: Always
    ports:
      - containerPort: 50051
        protocol: TCP
    #command: ['sh', '-c', "until nslookup pokmonserver-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for server service; sleep 2; done"]
  - name: pokmon-mongodb
    image: mongo:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 27017
        protocol: TCP
    #command: ['sh', '-c', "until nslookup mongodb-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mongoDB; sleep 2; done"]