---
apiVersion: v1
kind: Service
metadata:
  name: pokmonserver-service
spec:
  ports:
  - protocol: TCP
    port: 50051
  type: LoadBalancer
  selector:
    app: application
---
apiVersion: v1
kind: Service
metadata:
  name: pokmongame-service
spec:
  ports:
  - protocol: TCP
    port: 8080
  type: LoadBalancer
  selector:
    app: application2  
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  ports:
  - protocol: TCP
    port: 27017
  type: NodePort
  selector:
    app: mongodb