apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulset
  labels:
    app: mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        envFrom:
        - configMapRef:
            name: mongodb-configuration
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-data
          mountPath: /var/lib/mongodb/data
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pv-claim

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pokmon-server-statefulset
  labels:
    app: pokmon-server
spec:
  serviceName: "pokmonserver-service"
  replicas: 1
  selector:
    matchLabels:
      app: pokmon-server
  template:
    metadata:
      labels:
        app: pokmon-server
    spec:
      containers:
      - name: pokmon-server
        image: sluu3/pokmonserver:latest
        envFrom:
        - configMapRef:
            name: pokserver-configuration
        ports:
        - containerPort: 50051
          name: pokmon-server
        volumeMounts:
        - name: pokserver-data
          mountPath: /var/lib/pokserver/data
      volumes:
      - name: pokserver-data
        persistentVolumeClaim:
          claimName: pokserver-pv-claim

